apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-simple-website2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-simple-website2
  template:
    metadata:
      labels:
        app: my-simple-website2
    spec:
      containers:
        - name: my-simple-website2
          image: my-simple-website2:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
